### PR TITLE
Enhance Scraping and Caching for Bible Books with Optimized URL Handling

### PR DESCRIPTION
**Pull request by ralaska**
# Enhanced Bible Scraping with Better URL Handling & Caching

The html seems to have changed on the website, and nothing worked. Fixed a bunch of issues with the Hebrew and English Bible scraping code, mainly around how we handle Psalms URLs, added some caching to make things faster, and fixed deprecated parsing code due to possible website changes. Here's what I did:

### URL Fixes for Psalms (bookData.py)
Fixed that annoying problem with Psalms chapters over 99 - turns out Mechon-Mamre uses a weird URL pattern for these (like adding 'a' through 'e' for chapters 100-150). Updated the URL generator to handle this properly.

### Added HTML Caching (fetchPages.py)
Got tired of hammering their server every time we run the script, so:
- Set up a data/html folder to cache the pages
- Now checks cache before downloading anything new
- Uses MD5 for filenames to keep things clean

### Script Parsing Improvements (bookData.py)
Fixed some nasty bugs in how we parse the script tags:
- Switched from script.string to get_text() to fix those NoneType errors
- Added checks for args length (was causing index errors)
- Better error handling when the chapters function is weird

### Better Verse Parsing (chapterData.py)
Cleaned up how we handle verses:
- Got rid of those Hebrew markers (פ and ס) that were cluttering everything
- Skips reference tags now
- Added regex to clean up any leftover {...} stuff

### General Cleanup
- Better error messages (actually helpful ones)
- Won't crash on bad data anymore
- Added some debug prints (commented out but there if needed)

## What's Better Now
- Way faster with caching
- Actually gets all Psalms chapters correctly
- Doesn't break on weird HTML structures
- Clean verse output without all the extra markers

## Testing Done
- Ran through all 150 Psalms chapters - all good
- Checked the verse cleaning works
- Tested with different books to make sure nothing broke

---

Let me know if you run into any issues. Should be much more stable now.

### CODE REVIEW

**Comment by paceaux** [comment]
I'm going to try and do a thorough review of this in the next day or two. Not because I don't believe you, but because I want to learn. 


Thank you so much for doing this. I wrote this code before I knew sefaria.org existed and I wanted to build my own app.

**Comment by paceaux** [comment]
I'm going to try and do a thorough review of this in the next day or two. Not because I don't believe you, but because I want to learn. 


Thank you so much for doing this. I wrote this code before I knew sefaria.org existed and I wanted to build my own app. 


BTW @ralaska I have some other projects that I think I'd  _really_ like to collaborate with you on. Seems like you've got some solid experience with this stuff. 

If you go to paceaux.com or my blog, you can find ways to contact me.

**Comment by ralaska** [comment]
This is amazing thank you for pointing me to sefaria.org. 

I just pushed additional code just to be able to validate mechon-mamre.org content. 

The new file:

src/validator/tanakhVerseValidator.py

now has `tanakh` variable which now holds all the books and chapter counts and verse counts from `mechon-mamre.org`.

I needed a way to validate if the content on `mechon-mamre.org` is correct at verse level, so currently I am comparing it to `bible_kjv` (which I know isn't a good idea but for now I think it would do, I needed some kind of baseline to be able to compare)

More code to review for you :)

And thank you for this project!

**Comment by ralaska** [comment]
sefaria.org is turning out to be a great treasure for me. Did you write something for this?
sefaria.org
If not I can start working on it.
By the way I own https://bible.peplamb.com

**Comment by paceaux** [comment]
@ralaska You may be interested in [berea](https://github.com/paceaux/Berea) which uses an open and free version of the bible API. 

I think I actually stopped working on this because someone turned me on to Sefaria.

**Review by paceaux — APPROVED** [review]

**Comment by paceaux** [comment]
I'm approving this. These look like good changes and I appreciate the fact that it's more performant.

**Pull request merged**
